[package]
name = "orderbook"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rust_decimal = "1"
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.0"